name: CI/CD Pipeline with Observability

on:
  push:
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          npm install
        env:
          OBSERVABILITY_JOB_NAME: "Install Dependencies"

      - name: Run Tests
        run: |
          npm test
        env:
          OBSERVABILITY_JOB_NAME: "Run Tests"

      - name: Build Application
        run: |
          npm run build
        env:
          OBSERVABILITY_JOB_NAME: "Build Application"

      - name: Push Metrics to Prometheus
        run: |
           echo "Simulando envío de métricas para ${{ env.OBSERVABILITY_JOB_NAME }}"
